spring.application.name=resturarent-system

# Load .env file
spring.config.import=optional:file:.env.properties

# Cloud Database
spring.datasource.url=jdbc:mysql://syncserve-database-syncserve-93.j.aivencloud.com:28248/defaultdb?useSSL=true&sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT (keep yours)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# Server
server.port=8080

# Hikari pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.test-query=SELECT 1

#Email service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cravehouse.system.dev@gmail.com
spring.mail.password=qogkpevwsxibwmlg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# Testing switch:
# true  -> force email failure intentionally
# false -> use real SMTP behavior
app.email.force-fail=false