package com.ByteKnights.com.resturarent_system.entity;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    PASSWORD_CHANGED,

    STAFF_CREATED,
    STAFF_UPDATED,
    STAFF_ACTIVATED,
    STAFF_DEACTIVATED,
    INVITE_RESENT,

    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    ROLE_PERMISSIONS_UPDATED,

    BRANCH_CREATED,
    BRANCH_UPDATED,
    BRANCH_ACTIVATED,
    BRANCH_DEACTIVATED,

    GLOBAL_CONFIG_UPDATED,
    BRANCH_CONFIG_UPDATED,
    BRANCH_OPERATING_HOURS_UPDATED
}