package com.ByteKnights.com.resturarent_system.entity;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    PASSWORD_CHANGED,

    STAFF_CREATED,
    STAFF_UPDATED,
    STAFF_ACTIVATED,
    STAFF_DEACTIVATED,
    INVITE_RESENT,

    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    ROLE_PERMISSIONS_UPDATED,

    BRANCH_CREATED,
    BRANCH_UPDATED,
    BRANCH_ACTIVATED,
    BRANCH_DEACTIVATED,

    GLOBAL_CONFIG_UPDATED,
    BRANCH_CONFIG_UPDATED,
    BRANCH_OPERATING_HOURS_UPDATED,

    MENU_CATEGORY_CREATED,
    MENU_CATEGORY_UPDATED,
    MENU_CATEGORY_DELETED,

    MENU_ITEM_CREATED,
    MENU_ITEM_UPDATED,
    MENU_ITEM_APPROVED,
    MENU_ITEM_REJECTED,
    MENU_ITEM_AVAILABILITY_CHANGED,
    MENU_ITEM_DELETED,

    TABLE_CREATED,
    TABLE_UPDATED,
    TABLE_STATUS_UPDATED,
    TABLE_DELETED,

    QR_CODE_CREATED,
    QR_CODE_REVOKED,
    QR_CODE_REGENERATED,

    QR_SESSION_STARTED,
    QR_SESSION_ENDED,

    ORDER_CREATED,
    ORDER_CANCELLED,

    PAYMENT_STATUS_UPDATED,

    CHEF_REQUEST_CREATED,
    CHEF_REQUEST_RESOLVED,
    CHEF_ASSIGNED,
    CHEF_CHECKED_IN,
    CHEF_CHECKED_OUT,
    CHEF_WORK_STATUS_UPDATED,
    ORDER_ON_HOLD,
    MEAL_STARTED,
    MEAL_COMPLETED,

    INVENTORY_ITEM_CREATED,
    INVENTORY_ITEM_RESTOCKED,
    INVENTORY_STOCK_REMOVED,
    INVENTORY_ITEM_CORRECTED,

    DRIVER_ASSIGNED,
    DELIVERY_ACCEPTED,
    DELIVERY_REJECTED,
    DELIVERY_STATUS_UPDATED,
    DELIVERY_ONLINE_STATUS_UPDATED,

    REPORT_GENERATED
}