package com.ByteKnights.com.resturarent_system.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity representing an internal Purchase Order (PO) raised by a manager
 * against a vendor. The PO is an internal record only — the manager contacts
 * the vendor externally (phone, message, etc.). No emails are sent.
 *
 * Lifecycle: DRAFT → SUBMITTED → PARTIALLY_RECEIVED / RECEIVED / CANCELLED
 */
@Entity
@Table(name = "purchase_orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PurchaseOrder {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The branch this PO belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "branch_id", nullable = false)
    private Branch branch;

    /** The vendor this PO is raised against. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vendor_id", nullable = false)
    private Vendor vendor;

    /**
     * Auto-generated human-readable PO number.
     * Format: PO-{YEAR}-{zero-padded sequence}, e.g. "PO-2026-047".
     * Generated by the service layer before saving.
     */
    @Column(name = "po_number", unique = true, nullable = false, length = 30)
    private String poNumber;

    /** Current lifecycle status of this Purchase Order. */
    @Enumerated(EnumType.STRING)
    @Builder.Default
    @Column(nullable = false, length = 30)
    private PurchaseOrderStatus status = PurchaseOrderStatus.SUBMITTED;

    /** The expected date on which the vendor should deliver the goods. */
    @Column(name = "expected_delivery_date")
    private LocalDate expectedDeliveryDate;

    /** Optional notes from the manager (e.g., "Deliver before lunch service"). */
    @Column(columnDefinition = "TEXT")
    private String notes;

    /** The staff member (manager) who created this PO. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by_staff_id", nullable = false)
    private Staff createdBy;

    /** Timestamp when this PO was first created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }
}
